spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/world?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver